export {default as ModalUser} from './ModalUser'
export {default as ModalVideo} from './ModalVideo'
export {default as ModalShare} from './ModalShare'
export {default as ModalCategory} from './ModalCategory'
export {default as ModalMyVideos} from './ModalMyVideos'
export {default as ModalEditVideo} from './ModalEditVideo'
export {default as ModalCommentary} from './ModalCommentary'
export {default as ModalVideoSearch} from './ModalVideoSearch'
export {default as ModalMyCategories} from './ModalMyCategories'
export {default as ModalEditCategory} from './ModalEditCategory'
export {default as ModalVideoDetails} from './ModalVideoDetails'
export {default as ModalYoutubeSearch} from './ModalYoutubeSearch'
export {default as ModalForgotPassword} from './ModalForgotPassword'
export {default as ModalRecoveryPassword} from './ModalRecoveryPassword'

