export { default as ModalVideo } from './ModalVideo'
export { default as ModalShare } from './ModalShare'
export { default as ModalCategory } from './ModalCategory'
export { default as ModalMyCategories } from './ModalMyCategories'
export { default as ModalForgotPassword } from './ModalForgotPassword'
export { default as ModalEditCategory } from './ModalEditCategory'
export { default as ModalRecoveryPassword } from './ModalRecoveryPassword'
export { default as ModalConfirmEmail } from './ModalConfirmEmail'
